name: Ondřej Mirtes
description: Vývojář s nadšením pro user experience, Apple, počítačové hry, cestování a kofein.
markdown: rdiscount
rdiscount:
  extensions: [ smart ]
pygments: true
baseurl: "http://ondrej.mirtes.cz"
permalink: /:title.html
yearly_archive:
  path: archiv
homepage_limit: 10
timezone: Europe/Prague
exclude: [ README.md, Makefile ]
