name: Ondřej Mirtes
description: Vývojář s nadšením pro user experience, Apple, počítačové hry, cestování a kofein.
markdown: kramdown
kramdown:
  parse_block_html: true
  smart_quotes: sbquo,lsquo,bdquo,ldquo
highlighter: pygments
pygments_options:
  tabsize: 4
baseurl: "https://ondrej.mirtes.cz"
permalink: /:title.html
yearly_archive:
  path: archiv
homepage_limit: 10
timezone: Europe/Prague
exclude: [ README.md, Makefile ]
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
